// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackaton

#ifndef _UI_COMP_BACKGROUND1_H
#define _UI_COMP_BACKGROUND1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Background1
#define UI_COMP_BACKGROUND1_BACKGROUND1 0
#define _UI_COMP_BACKGROUND1_NUM 1
lv_obj_t * ui_Background1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
