// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackaton

#include "../ui.h"


// COMPONENT Background1

lv_obj_t * ui_Background1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Background1;
    cui_Background1 = lv_img_create(comp_parent);
    lv_obj_set_width(cui_Background1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Background1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Background1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Background1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Background1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BACKGROUND1_NUM);
    children[UI_COMP_BACKGROUND1_BACKGROUND1] = cui_Background1;
    lv_obj_add_event_cb(cui_Background1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Background1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Background1_create_hook(cui_Background1);
    return cui_Background1;
}

