// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackaton

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_dashboard3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_PlayButton, 80);
    lv_obj_set_height(ui_PlayButton, 40);
    lv_obj_set_x(ui_PlayButton, 113);
    lv_obj_set_y(ui_PlayButton, 90);
    lv_obj_set_align(ui_PlayButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xEE3C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayLabel = lv_label_create(ui_PlayButton);
    lv_obj_set_width(ui_PlayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PlayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlayLabel, "Play");

    ui_TempPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_TempPanel, 144);
    lv_obj_set_height(ui_TempPanel, 30);
    lv_obj_set_x(ui_TempPanel, 83);
    lv_obj_set_y(ui_TempPanel, -41);
    lv_obj_set_align(ui_TempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempPanel, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_TempPanel);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempLabel, "Temp: ");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_HumPanel, 144);
    lv_obj_set_height(ui_HumPanel, 30);
    lv_obj_set_x(ui_HumPanel, 83);
    lv_obj_set_y(ui_HumPanel, -7);
    lv_obj_set_align(ui_HumPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumPanel, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumLabel = lv_label_create(ui_HumPanel);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HumLabel, "Hum: ");
    lv_obj_set_style_text_color(ui_HumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_AccPanel, 144);
    lv_obj_set_height(ui_AccPanel, 30);
    lv_obj_set_x(ui_AccPanel, 83);
    lv_obj_set_y(ui_AccPanel, 27);
    lv_obj_set_align(ui_AccPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AccPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AccPanel, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccLabel = lv_label_create(ui_AccPanel);
    lv_obj_set_width(ui_AccLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AccLabel, "Acc: (x, y, z) ");
    lv_obj_set_style_text_color(ui_AccLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimePanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_TimePanel, 144);
    lv_obj_set_height(ui_TimePanel, 30);
    lv_obj_set_x(ui_TimePanel, 88);
    lv_obj_set_y(ui_TimePanel, -106);
    lv_obj_set_align(ui_TimePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimePanel, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_TimePanel);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel, "Time:");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PlayButton, ui_event_PlayButton, LV_EVENT_ALL, NULL);

}
