// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackaton

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x102462), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button0 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button0, 60);
    lv_obj_set_height(ui_Button0, 60);
    lv_obj_set_x(ui_Button0, -68);
    lv_obj_set_y(ui_Button0, -64);
    lv_obj_set_align(ui_Button0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button1, 60);
    lv_obj_set_height(ui_Button1, 60);
    lv_obj_set_x(ui_Button1, -2);
    lv_obj_set_y(ui_Button1, -64);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 60);
    lv_obj_set_height(ui_Button2, 60);
    lv_obj_set_x(ui_Button2, 62);
    lv_obj_set_y(ui_Button2, -64);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 60);
    lv_obj_set_x(ui_Button3, -68);
    lv_obj_set_y(ui_Button3, 2);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button4, 60);
    lv_obj_set_height(ui_Button4, 60);
    lv_obj_set_x(ui_Button4, -2);
    lv_obj_set_y(ui_Button4, 2);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button5, 60);
    lv_obj_set_height(ui_Button5, 60);
    lv_obj_set_x(ui_Button5, 62);
    lv_obj_set_y(ui_Button5, 2);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button6, 60);
    lv_obj_set_height(ui_Button6, 60);
    lv_obj_set_x(ui_Button6, -68);
    lv_obj_set_y(ui_Button6, 68);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 61);
    lv_obj_set_height(ui_Button7, 60);
    lv_obj_set_x(ui_Button7, -2);
    lv_obj_set_y(ui_Button7, 68);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconX = lv_img_create(ui_Button7);
    lv_img_set_src(ui_iconX, &ui_img_x_icon2_png);
    lv_obj_set_width(ui_iconX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconX, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconX, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button8, 60);
    lv_obj_set_height(ui_Button8, 60);
    lv_obj_set_x(ui_Button8, 62);
    lv_obj_set_y(ui_Button8, 68);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconO = lv_img_create(ui_Button8);
    lv_img_set_src(ui_iconO, &ui_img_o_icon3_png);
    lv_obj_set_width(ui_iconO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButton = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_BackButton, 40);
    lv_obj_set_height(ui_BackButton, 40);
    lv_obj_set_x(ui_BackButton, -130);
    lv_obj_set_y(ui_BackButton, 90);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0xEE3C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel2 = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_BackLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel2, "Back");

    ui_ResetButton = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ResetButton, 40);
    lv_obj_set_height(ui_ResetButton, 40);
    lv_obj_set_x(ui_ResetButton, 130);
    lv_obj_set_y(ui_ResetButton, -89);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetButton, lv_color_hex(0xEE3C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetLabel = lv_label_create(ui_ResetButton);
    lv_obj_set_width(ui_ResetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetLabel, "Reset");

    ui_PlayerButton = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_PlayerButton, 51);
    lv_obj_set_height(ui_PlayerButton, 47);
    lv_obj_set_x(ui_PlayerButton, -130);
    lv_obj_set_y(ui_PlayerButton, -89);
    lv_obj_set_align(ui_PlayerButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlayerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlayerButton, lv_color_hex(0xEE3C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayerLabel = lv_label_create(ui_PlayerButton);
    lv_obj_set_width(ui_PlayerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlayerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PlayerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlayerLabel, "Play\nsecond");
    lv_obj_set_style_text_color(ui_PlayerLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlayerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button0, ui_event_Button0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayerButton, ui_event_PlayerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
