// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: hackaton

#include "btnqueue.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include "ui.h"

void startBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_start, pdFALSE);
}

void provisionBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_prov, pdFALSE);
}

void connectBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_conn, pdFALSE);
}

void playBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_play, pdFALSE);
}

void field0Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p0, pdFALSE);
}

void field1Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p1, pdFALSE);
}

void field2Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p2, pdFALSE);
}

void field3Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p3, pdFALSE);
}

void field4Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p4, pdFALSE);
}

void field5Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p5, pdFALSE);
}

void field6Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p6, pdFALSE);
}

void field7Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p7, pdFALSE);
}

void field8Cb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_p8, pdFALSE);
}

void backBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_back, pdFALSE);
}

void resetBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_reset, pdFALSE);
}

void playerBtnCb(lv_event_t *e)
{
    // Your code here
    xQueueSendFromISR(btn_queue, &btn_player, pdFALSE);
}
